_prefs: 
  mapid: planemad.66359ac0
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 83.5181
  - 28.0817
  - 6
description: Simple print friendly style that shows major highways and cities.
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 6
name: Highway Atlas
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
  - highways.mss
template: ''
